// brewcode-next/components/Navbar.tsx
import React, { FC } from "react";
import { CodeXml, AlignRight } from "lucide-react";
import Link from "next/link";
import { NavbarProps } from "@/types/type";

const Navbar: FC<NavbarProps> = ({ scroll }) => {
  return (
    <nav className="flex flex-row items-center justify-between px-20 py-10 max-md:px-10 ">
      {/* logo */}
      <Link href={"/"}>
        <CodeXml />
      </Link>
      {/* Navigations */}
      <section className="flex flex-row gap-20 max-md:hidden">
        <button
          className="outline-none hover:underline"
          onClick={() => scroll("home")}
        >
          Home
        </button>

        <button
          className="outline-none hover:underline"
          onClick={() => scroll("about")}
        >
          About
        </button>
        <button
          className="outline-none hover:underline"
          onClick={() => scroll("selling")}
        >
          Best Selling
        </button>
      </section>

      {/* responsive navigations */}
      <section className=" flex-row gap-20 hidden max-md:flex">
        <button>
          <AlignRight />
        </button>
      </section>
    </nav>
  );
};

export default Navbar;

// lensshare/client/src/components/root/Navbar.vue
<script setup lang="ts">
import { Aperture } from "lucide-vue-next";
import scrollTo from "../../utils/root/scrollTo";
</script>
<template>
  <header class="absolute w-full">
    <nav class="flex justify-between items-center max-w-full px-20 py-5">
      <!-- logo -->
      <a href="/"><Aperture size="35" /></a>
      <!-- navs -->
      <div class="flex gap-10">
        <button
          class="cursor-pointer hover:underline"
          @click="() => scrollTo('home')"
        >
          Home
        </button>
        <button
          class="cursor-pointer hover:underline"
          @click="() => scrollTo('about')"
        >
          About
        </button>
        <button
          class="cursor-pointer hover:underline"
          @click="() => scrollTo('contact')"
        >
          Contact
        </button>
      </div>
      <!-- routes -->
      <a href="/dashboard">Rent Now!</a>
    </nav>
  </header>
</template>
