// next-brewcode/components/Navbar.tsx
"use client";

import React, { useState } from "react";
import { Coffee, AlignLeft } from "lucide-react";
import Link from "next/link";
const Navbar = () => {
  const [navToggle, setNavToggle] = useState(false);
  return (
    <nav className="bg-coffee flex max-w-full items-center justify-between px-20 py-10">
      <Link href="/" className="text-6xl font-bold">
        <Coffee />
      </Link>
      <div className="relative flex flex-col items-end gap-3">
        <button
          className=" w-fit rounded-md border border-white p-1 outline-none transition-all hover:bg-white hover:text-[#6F4E37]"
          onClick={() => setNavToggle(!navToggle)}
        >
          <AlignLeft />
        </button>
        <div
          className={`${
            navToggle ? "block" : "hidden"
          } absolute top-12 flex flex-col gap-4 border border-white px-4 py-2`}
        >
          <Link href="/auth">Login</Link>
          <Link href="/auth/register">Register</Link>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// brew-code/src/components/Navbar.svelte
<script>
	import { AlignLeft, Coffee } from 'lucide-svelte';
	let toggleNav = false;
</script>

<nav class="max-w-full flex justify-between items-center px-20 py-10 bg-coffee">
	<a href="/" class="text-6xl font-bold"><Coffee /></a>
	<div class="flex flex-col gap-3 items-end relative">
		<button
			class=" border border-white rounded-md p-1 w-fit hover:bg-white hover:text-[#6F4E37] outline-none transition-all"
			on:click={() => (toggleNav = !toggleNav)}><AlignLeft /></button
		>
		<div
			class={`${toggleNav ? 'block' : 'hidden'} absolute top-12 border border-white px-4 py-2 flex flex-col gap-4`}
		>
			<a href="/auth">Login</a>
			<a href="/auth/register">Register</a>
		</div>
	</div>
</nav>
